### ISSUE TITLE
error with Gatsby v2

### ISSUE THREAD

**Issue by kremalicious** [getchalk/gatsby-plugin-meta-redirect#5]
When using with Gatsby `v2.0.0-rc.4` I get this when running `gatsby build`:

```
error Plugin gatsby-plugin-meta-redirect returned an error

  ReferenceError: regeneratorRuntime is not defined
```

Not entirely sure if that's only because of Gatsby v2. Are you able to reproduce this?

And thanks for this plugin! Seems to be exactly what I need for solving https://github.com/kremalicious/gatsby-redirect-from/issues/7

**Comment by dannywils** [comment]
Hey, take a look at https://github.com/getchalk/gatsby-plugin-meta-redirect/issues/3#issuecomment-401539655

Adding `import 'regenerator-runtime/runtime';` in gatsby-config.js should work.

**Comment by kremalicious** [comment]
d'oh for not using the search, works like a charm, thank you!

![giphy-1](https://user-images.githubusercontent.com/90316/44855935-72f67500-ac6c-11e8-963f-b7483d34fec6.gif)

**Comment by JacobDFrank** [comment]
> Hey, take a look at [#3 (comment)](https://github.com/getchalk/gatsby-plugin-meta-redirect/issues/3#issuecomment-401539655)
> 
> Adding `import 'regenerator-runtime/runtime';` in gatsby-config.js should work.

How would you add this to your gatsby-config.js?

mine is currently this and I'm having the same issue.

module.exports = {
  siteMetadata: {
    title: 'Thought At Work 2018'
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sass',
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'UA-96615084-2',
        // Setting this parameter is optional
        anonymize: false
      }
    },
    'gatsby-transformer-remark',
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-meta-redirect',
  ]
};

**Comment by kremalicious** [comment]
@JacobDFrank put it just before the `module.exports` start so it ends up like this:

```js
import 'regenerator-runtime/runtime';
// or old-school require depending on your Gatsby version
// require('regenerator-runtime/runtime');

module.exports = {
  siteMetadata: {
    title: 'Thought At Work 2018'
  },
...
}
```

**Comment by JacobDFrank** [comment]
Thanks so much, that got it to work. I'm using v1 still (didn't wanna deal with the errors of upgrading just yet) and I had no idea how to figure out the import.
