### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by danpalmer** [getchalk/gatsby-plugin-meta-redirect#6]
Same issue as https://github.com/weirdpattern/gatsby-remark-embed-gist/pull/1 – it looks like the necessary dependency has disappeared in Gatsby 2.x.

**Comment by Akallabet** [comment]
This is happening for me as well

**Comment by stmcallister** [comment]
Also happening for me. I tried adding `babel-plugin-transform-runtime` to the package.json for this plugin, as well as my project, and I'm still getting the regeneratorRuntime error.

**Comment by ivanvanderbyl** [comment]
Given that every modern version of node supports async/await, I can't see why this is needed anymore.
