### ISSUE TITLE
Unsure how to use this plugin

### ISSUE THREAD

**Issue by Mozart409** [getchalk/gatsby-plugin-meta-redirect#9]
Hi, I wanted to ask where to put the "createRedirects". Should I pass them as options in the gatsby-config.js, for the plugin? e.g.
{
      resolve: `gatsby-plugin-meta-redirect`,
      options: {
        createRedirect({ fromPath: '/old-url', toPath: '/new-url', isPermanent: true });
createRedirect({ fromPath: '/url', toPath: '/zn-CH/url', Language: 'zn' });
      }
    }, 

this wouldn't make sense, would it?
Thanks

**Comment by t-lochhead** [comment]
Came here with the same question.

Found this code as an example to refer to:
https://github.com/armurad/test/blob/9a75affdd4f8970d4c5a614140f06210adb10d5f/www/gatsby-node.js
